name: Test

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9.1
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - name: Generate file
        run: |
          python3 --version
          python3 main.py

      - name: Commit to the repo
        run: |
          git config --global user.name "JoseDeFreitas/JoseDeFreitas"
          git config --global user.email "joselocotote26@gmail.com"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m 'Update generated files' || echo
          git push
